AdminPage/book/controllers/HomeController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class HomeController extends Controller {

    public $layout = "home_layout_vinh";
   // public $layout = "homelayout";
    

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex() {
        return $this->render('index');
    }

    public function actionView() {
        $id = $_GET['book_id'];
        $model = \app\models\Book::findOne($id);
        return $this->render('view', ['book' => $model]);
    }

    public function actionType() {

        isset($_GET['pr_id']) ? $pr_id = $_GET['pr_id'] : $pr_id = 0;
        isset($_GET['cate_id']) ? $cate_id = $_GET['cate_id'] : $cate_id = 0;

        return $this->render('type', ['pr_id' => $pr_id, 'cate_id' => $cate_id]);
    }

    public function actionDetail() {
        return $this->render('detail');
    }

}

AdminPage/book/views/home/detail.php
<style>
    .pcat{
        padding: 10px;
    }
</style>
<div class="contentabc">   
    <div class="right">
        <ul id="crumbs">
            <li><a href="hanhtrangvaodaihoc.html">
                    <img alt="Trở về trang chủ" src="http://hanhtrangvaodaihoc.com/images/home.png" /></a></li>
            <li><a href="lop-10-c41.aspx.html">LỚP 10</a></li><li><a href="cac-mon-khac-10-c71.aspx.html">Các môn khác 10</a></li>
        </ul>
        <div class="clear">
        </div>
        <div class="title-pcat">
            <div class="f">
                &nbsp;</div>
            <h1>
                Các môn khác 10</h1>
        </div>
        <div class="clear">
        </div>

        <div class="pcat">
            <img src="http://hanhtrangvaodaihoc.com/upload/images/products/Nhung-Vien-Kim-Cuong-Trong-Hoa-Hoc.jpg"/>
            <img src="http://hanhtrangvaodaihoc.com/upload/images/products/Nhung-Vien-Kim-Cuong-Trong-Hoa-Hoc.jpg"/>
            <img src="http://hanhtrangvaodaihoc.com/upload/images/products/Nhung-Vien-Kim-Cuong-Trong-Hoa-Hoc.jpg"/>
            <img src="http://hanhtrangvaodaihoc.com/upload/images/products/Nhung-Vien-Kim-Cuong-Trong-Hoa-Hoc.jpg"/>
        </div>

        <div id="ContentPlaceHolder1_ProductListControl1_pnlPaging" class="paging">

        </div>

    </div>

</div>

AdminPage/book/views/home/index.php
<div class="contentabc">

    <style>
        .Slides_Container img{
            width: 540px;
            height: 240px;
        }
        .ctl03_rpt1_img{
            width: 130px;
            height: 160px;
        }
    </style>

    <div  width="540" height="280">

    </div>

    <div class="right-home">
        <iframe scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:220px; height:278px; margin-left:-3px" allowTransparency="true"></iframe>

    </div>
    <div class="clear">
    </div>

    <div class="newletter">

        <input name="HomeNewsLetterControl1$txtNewLetter" type="text" value="Địa chỉ email của bạn" id="HomeNewsLetterControl1_txtNewLetter" class="txtNewletter" />
        <input type="submit" name="HomeNewsLetterControl1$btnNewletter" value="ĐĂNG KÝ" onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions( & quot; HomeNewsLetterControl1$btnNewletter & quot; , & quot; & quot; , true, & quot; 1 & quot; , & quot; & quot; , false, false))" id="HomeNewsLetterControl1_btnNewletter" />
        <span id="HomeNewsLetterControl1_RequiredFieldValidator1" style="display:none;"></span>
        <span id="HomeNewsLetterControl1_RegularExpressionValidator1" style="display:none;"></span>
        <div id="HomeNewsLetterControl1_ValidationSummary1" style="display:none;">

        </div>

    </div>

    <div class="home-middle">
        <div style="float:left; margin-right:10px">
        </div>
    </div>

    <div class="clear">
    </div>

    <div class="clear">
    </div>

    <div class="clear">
    </div>
    <?php $url = \Yii::$app->getUrlManager()->createUrl(['home/view', 'book_id' => 1]); ?>
    <div id="HomeBestSellerControl1_pnlBanChay" class="box-home" style="border-left: none; border-right: none; width: 998px">
        <div class="title">
            <h3>Sản phẩm bán chạy</h3>
        </div>
        <div class="clear">
        </div>
        <div>
            <ul class="mycarousel jcarousel-skin-tango">

                <?php for ($i = 0; $i < 5; $i++) { ?>
                    <li>
                        <a id="HomeBestSellerControl1_rpt1_hplImg_0" href="<?= $url ?>">
                            <img class="ctl03_rpt1_img" src="http://localhost/book/uploads/20150705122843.jpg" />
                        </a>
                        <div class="model-name">
                            <a id="HomeBestSellerControl1_rpt1_hplTitle_0" href="<?= $url ?>">Những Viên Kim Cương Trong Hoá Học</a>
                        </div>
                        <div id="HomeBestSellerControl1_rpt1_price_old_0" class="price-old">
                            450.000 VNĐ
                        </div>
                        <div class="price">
                            428.000 VNĐ
                        </div>
                    </li>
                <?php } ?>

            </ul>
        </div>
    </div>

    <?php
    $prList = app\models\ProductList::find()->all();
    foreach ($prList as $key => $value) {
        ?>
        <div class="box-home">
            <div class="title">
                <h3><?= $value['name'] ?></h3>
                <div class="sub">
                    <?php
                    $cate = app\models\Category::find(['product_list_id' => $value['id']])
                                    ->innerJoin("tbl_book_type as tp", 'tp.category_id = tbl_category.id')
                                    ->andWhere(['tp.product_list_id' => $value['id']])->all();
                    foreach ($cate as $key => $value1) {
                        echo \yii\helpers\Html::a($value1['name'], ['type', 'pr_id' => $value['id'], 'cate_id' => $value1['id']]) . ' | ';
                    }
                    ?>
                </div>
            </div>

            <div class="clear">
            </div>
            <div id="ctl03_pnlRecord">
                <ul class="mycarousel jcarousel-skin-tango">

                    <?php
                    $book = app\models\Book::find()
                                    ->innerJoin("tbl_book_type as tp", 'tbl_book.type_id = tp.id')
                                    ->andWhere(['tp.product_list_id' => $value['id']])->all();
                    foreach ($book as $key => $value1) {
                        ?>

                        <li>
                            <a id="ctl03_rpt1_hplImg_0" href="<?= $url ?>">
                                <img class="ctl03_rpt1_img" src="<?= app\models\Images::findOne($value1['image_id']) ? "http://localhost/book/uploads/" . (app\models\Images::findOne($value1['image_id'])->name . '.' . app\models\Images::findOne($value1['image_id'])->ext) : '' ?>" />
                            </a>
                            <div class="model-name">
                                <?= \yii\helpers\Html::a($value1['name'], ['view', 'book_id' => $value1['id']]) ?>
                            </div>
                            <div id="ctl03_rpt1_price_old_0" class="price-old">
                                450.000 VNĐ
                            </div>
                            <div class="price">
                                428.000 VNĐ
                            </div>
                        </li>

                    <?php }
                    ?>

                </ul>
            </div>
        </div>


    <?php } ?>

</div>

AdminPage/book/views/home/slideshow.php
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="css/normalize.min.css">
  <link rel="stylesheet" href="css/main.css">

  <script src="js/modernizr-2.6.2.min.js"></script>

  <div class="wrapper">
    <ul class="slider">
      <li><img src="img/slide-1.jpg" /></li>
      <li><img src="img/slide-2.jpg" /></li>
      <li><img src="img/slide-3.jpg" /></li>
    </ul>
  </div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/jquery-1.9.1.min.js"><\/script>')</script>

  <script src="js/main.js"></script>

AdminPage/book/views/home/type.php
<style>
    .ctl03_rpt1_img{
        width: 160px;
        height: 160px;
    }
</style>

<div class="contentabc">   
    <div class="right">
        <ul id="crumbs">
            <li><a href="hanhtrangvaodaihoc.html">
                    <img alt="Trở về trang chủ" src="http://localhost/book/images/home.png" /></a></li>
            <li><a href="lop-10-c41.aspx.html"><?= app\models\ProductList::findOne($pr_id)->name ?></a>
        </ul>
        <div class="clear">
        </div>
        <div class="title-pcat">
            <div class="f">
                &nbsp;</div>
            <h1><?= $cate_id ? app\models\Category::findOne($cate_id)->name : "Tất cả sách" ?></h1>
        </div>
        <div class="clear">
        </div>

        <div class="pcat">
            <ul>

                <?php
                if (!$cate_id) {
                    $book = app\models\Book::find()
                                    ->innerJoin("tbl_book_type as tp", 'tbl_book.type_id = tp.id')
                                    ->andWhere(['tp.product_list_id' => $pr_id])->all();
                } else {
                    $book = app\models\Book::find()
                                    ->innerJoin("tbl_book_type as tp", 'tbl_book.type_id = tp.id')
                                    ->andWhere(['tp.product_list_id' => $pr_id, 'tp.category_id' => $cate_id])->all();
                }
                foreach ($book as $key => $value) {
                    ?>

                    <li>
                        <a id="ctl03_rpt1_hplImg_0" href="#">
                            <img class="ctl03_rpt1_img" src="<?= app\models\Images::findOne($value['image_id']) ? "http://localhost/book/uploads/" . (app\models\Images::findOne($value['image_id'])->name . '.' . app\models\Images::findOne($value['image_id'])->ext) : '' ?>" />
                        </a>
                        <div class="model-name">
                            <?= \yii\helpers\Html::a($value['name']) ?>
                        </div>
                        <div id="ctl03_rpt1_price_old_0" class="price-old">
                            450.000 VNĐ
                        </div>
                        <div class="price">
                            428.000 VNĐ

                            <div id="ctl03_rpt1_saleoff_0" class="dis-price">
                                -5%
                            </div>
                        </div>
                    </li>

                <?php }
                ?>

            </ul>
        </div>

        <div class="clear">
        </div>
        <div class="clear">
        </div>
        <div id="ContentPlaceHolder1_ProductListControl1_pnlPaging" class="paging">



        </div>

    </div>

</div>

AdminPage/book/views/home/view.php
<div class="contentabc">

    <div class="left">

        <div class="menu-left">
            <div class="title">
                <h2>
                    SÁCH LUYỆN THI ĐẠI HỌC 2015</h2>
            </div>
            <div class="clear">
            </div>
            <div class="body">

            </div>
        </div>

        <div class="clear">
        </div>

    </div>
    <div class="right">
        <ul id="crumbs">
            <li><a href="hanhtrangvaodaihoc.html">
                    <img alt="Trở về trang chủ" src="http://hanhtrangvaodaihoc.com/images/home.png">
                </a>
            </li>

            <li><a href="sach-luyen-thi-dai-hoc-2015-c122.aspx.html"></a>
            </li>
            <li><a href="mon-vat-ly-c45.aspx.html">MÔN VẬT LÝ</a>
            </li>
        </ul>
        <div class="clear">
        </div>
        <input type="hidden" name="ctl00$ContentPlaceHolder1$hdfID" id="ContentPlaceHolder1_hdfID" value="2359">
        <div class="pdetails">
            <div class="details-img">


                <img id="ContentPlaceHolder1_imgProduct" src="http://hanhtrangvaodaihoc.com/upload/images/products/Nhung-Vien-Kim-Cuong-Trong-Hoa-Hoc.jpg?width=160&height=160&quality=100">
            </div>
            <div class="details-info">
                <h1>
                    <?= $book['name'] ?></h1>
                <div id="ContentPlaceHolder1_pnlPInfo" class="if">

                    <p>
                        <b>
                            Tác giả: </b>
                        <a id="ContentPlaceHolder1_hplAuthor" href="http://hanhtrangvaodaihoc.com/product-list.aspx?tacgia= CHU VĂN BIÊN giáo viên chương trình bổ trợ kiến thức vật lí 12 kênh VTV2 - Đài truyền hình Việt Nam"> CHU VĂN BIÊN giáo viên chương trình bổ trợ kiến thức vật lí 12 kênh VTV2 - Đài truyền hình Việt Nam</a>
                        - <b>
                            Nhà xuất bản: </b>
                        <a id="ContentPlaceHolder1_hplNxb" href="http://hanhtrangvaodaihoc.com/product-list.aspx?nhaxuatban=5">ĐHQG Hà Nội</a>
                    </p>
                    <div class="left">
                        Tình trạng
                    </div>
                    <div class="right">
                        <img id="ContentPlaceHolder1_imgStatus" align="absmiddle" src="http://hanhtrangvaodaihoc.com/images/ico_available.gif">
                        &nbsp;Sẵn trong kho
                    </div>
                    <div class="clear">
                    </div>
                    <div class="left">
                        Trọng lượng
                    </div>
                    <div class="right">
                        600g
                    </div>
                    <div class="clear">
                    </div>
                    <div id="ContentPlaceHolder1_pnlBook">

                        <div class="left">
                            Số trang
                        </div>
                        <div class="right">
                            580
                        </div>
                        <div class="clear">
                        </div>

                        <div class="clear">
                        </div>
                        <div class="left">
                            Năm xuất bản
                        </div>
                        <div class="right">
                            2014
                        </div>
                        <div class="clear">
                        </div>

                    </div>

                    <!----->
                    <div class="left">
                        Công ty phát hành
                    </div>
                    <div class="right">
                        <a id="ContentPlaceHolder1_hplCongTyPhatHanh" href="http://hanhtrangvaodaihoc.com/product-list.aspx?phathanh=133">ABC</a>
                    </div>
                    <div class="clear">
                    </div>

                    <!----->
                    <div class="left">
                        Kích thước
                    </div>
                    <div class="right">
                        16 x 24
                    </div>
                    <div class="clear">
                    </div>


                    <!----->
                    <div class="left">
                        Hình thức:
                    </div>
                    <div class="right">

                    </div>
                    <div class="clear">
                    </div>

                    <!----->

                    <div class="clear">
                    </div>
                    <div class="left">
                        Giá: 
                    </div>
                    <div class="right">
                        <span class="price">
                            150.000 VNĐ</span>
                    </div>

                </div>
                <div class="clear">
                </div>

                <div>
                    <?= \yii\helpers\Html::a("Xem chi tiết sách", ['detail']) ?>
                </div>



                <a id="ContentPlaceHolder1_btnAddToCart" class="addcart" href="javascript:__doPostBack('ctl00$ContentPlaceHolder1$btnAddToCart','')">Thêm vào giỏ hàng</a>
                <script type="text/javascript">
                    function hethang() {
                        alert("Sản phẩm này hiện không sẵn có!");
                    }
                </script>

                <div class="clear">
                </div>
                <div class="action">

                </div>
                <div class="clear">
                </div>

                <div class="clear">
                </div>


            </div>
        </div>

        <div class="clear">
        </div>
    </div>
</div>